[pytest]
addopts =
    --alluredir=allure-results
    -v
    --tb=short

markers =
    smoke: Smoke-тесты базовой работоспособности
    regression: Регрессионные тесты
    filter: Тесты фильтрации каталога

filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
